name: Pre-commit
on:
  pull_request:

jobs:
  pre-commit:
    name: Pre-commit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: pip install pre-commit, detect-secrets

      - name: Pre-commit command
        run: pre-commit run --all-files
