name: Pre-commit
on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    name: Pre-commit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Pre-commit
      - uses: pre-commit/action@v3.0.0
